list_file: DATA/VITON-HD/vitonhd_train_mask.csv
sd3_model: stabilityai/stable-diffusion-3.5-large

size_h: 512
size_w: 384

mask_based: true           # Stage-1: true, Stage-2: false
invert_mask: true          # 의류 마스크를 뒤집어 Mi: keep=1 / hole=0 로 맞춤

# training
use_scaler: true
disable_text: true
lr: 1.0e-4
batch_size: 64
grad_accum: 1
max_steps: 256000
cond_dropout_p: 0.1
mixed_precision: bf16      # H100이면 bf16
seed: 1337
num_workers: 8

# preview
preview_infer_steps: 32
preview_seed: 1234
preview_strength: 0.6

# checkpoints & logging
save_epoch_ckpt: 15
default_resume_ckpt: None
resume_ckpt: None
save_root_dir: logs
save_name: catvton_sd35_mask
log_every: 10
image_every: 200
save_every: 12800

# adapter / projector
adapter_alpha: 1.0
norm_match_adapter: true
norm_match_clip: 5.0

# losses
hole_loss_weight: 2.0
keep_consistency_lambda: 0.1   # 0.05~0.2 권장 (0이면 비활성)

# runtime
hf_token: "${HUGGINGFACE_TOKEN}"
